Debian packageを生成するスクリプトを追加
tsukumijima/px4_drv pull request #1
Opened 2023-05-08 12:40 UTC by kazuki0824

mkdeb.bashを実行すると、Debianパッケージを生成するスクリプトを追加しました。

`mkdeb.bash`を実行すると、
- px4-drv.deb
- px4-drv_dkms-***.deb
の２つのファイルが生成されます。

これを、
```
sudo apt install px4-drv.deb px4-drv_dkms-***.deb -y
```
とする事でインストールができます。

2023-05-08 13:02 UTC, tsukumijima commented
良いと思います！ ただいくつか気になった箇所がありましたので、僭越ながらレビューさせていただきました。
よろしければ修正していただけると幸いです。

2023-05-08 13:05 UTC, tsukumijima commented
また、ファームウェアに関しては、深い階層ですが実は https://github.com/tsukumijima/px4_drv/blob/develop/winusb/pkg/DriverHost_PX4/it930x-firmware.bin に抽出済みのものがリポジトリ内に含まれています (WinUSB 用だが、Linux 向けにも同じものが使えるはず) 。

2023-05-08 13:10 UTC, kazuki0824 commented
> また、ファームウェアに関しては、深い階層ですが実は https://github.com/tsukumijima/px4_drv/blob/develop/winusb/pkg/DriverHost_PX4/it930x-firmware.bin に抽出済みのものがリポジトリ内に含まれています (WinUSB 用だが、Linux 向けにも同じものが使えるはず) 。

承知しました。これ使っちゃうようにします。

2023-05-08 13:10 UTC, kazuki0824 commented
> 良いと思います！ ただいくつか気になった箇所がありましたので、僭越ながらレビューさせていただきました。 よろしければ修正していただけると幸いです。

ちなみにレビュー内容はどこから見られますか？（こちらからは見つけられませんでした...）

2023-05-08 13:11 UTC, tsukumijima commented
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/39271166/236833093-4570bda6-4d16-40ac-a040-9e4a0c678741.png">
ちょうどこのコメントの上に載っているかと思うのですが…

2023-05-08 13:15 UTC, tsukumijima commented
ちなみにですが、マージし次第 GitHub Actions で amd64, arm64 (いずれも Ubuntu 20.04 LTS (glibc 2.31) 以降向け) の deb パッケージを自動ビルド/リリースできるようにしようと考え中です。

2023-05-08 13:51 UTC, kazuki0824 commented
> <img alt="image" width="1030" src="https://user-images.githubusercontent.com/39271166/236833093-4570bda6-4d16-40ac-a040-9e4a0c678741.png">
> ちょうどこのコメントの上に載っているかと思うのですが…

おかしいですね...そこには何も表示されてないです...
とにかく、内容はスクショからわかりましたので、指摘事項反映しておきました！

2023-05-08 13:53 UTC, tsukumijima commented
最終的なファイル構成は、下記のようにしていただけると助かります。

```
- - build_deb.sh
| - debian/
  | - control
| - Readme.md (追記)
```

2023-05-08 14:26 UTC, kazuki0824 commented
指摘を再度反映しました。

2023-05-08 14:37 UTC, tsukumijima commented on installer/README.md
> +sudo apt install px4-drv*.deb -y
基本的に `sudo apt install -y ./px4-drv_0.2.1_amd64.deb` のように相対パスか絶対パスで指定しないとパッケージ名と誤認されてインストールできなかったと思います（落とし穴）。

2023-05-08 14:37 UTC, tsukumijima commented on build_deb.sh
> +ARCH="amd64"
ラズパイなど ARM 環境でビルドする際にシェルスクリプトをいじらなくても良いように、amd64 か arm64 かは自動判定されるのが望ましいと思います。

2023-05-08 14:37 UTC, tsukumijima commented on README.md
> +sudo apt install px4-drv*.deb -y
`sudo apt install -y ./px4_drv-0.2.1_amd64.deb` のように相対パスか絶対パスでないとインストールに失敗すると思います。
あと、英字やコードと日本語との間には半角スペースを1つ空けてください。
また、周囲同様に見出し前の改行は1つ、見出し後の改行も1つに統一したいです。

2023-05-08 14:37 UTC, tsukumijima commented on DEBIAN/control
> +Maintainer: nns779 <25547272+nns779@users.noreply.github.com>
DEBIAN フォルダが大文字のままになっています。小文字にしてほしいです。

2023-05-08 16:28 UTC, kazuki0824 commented on build_deb.sh
> +ARCH="amd64"
今指摘もらって気づいたのですが、これそもそも"all"ですね。修正します

2023-05-08 16:29 UTC, kazuki0824 commented on build_deb.sh
> +ARCH="amd64"
DKMSはホストで随時コンパイル、バイナリブロブは置くだけなので、アーキテクチャは関係ないはずです。

2023-05-08 16:30 UTC, tsukumijima commented on build_deb.sh
> +ARCH="amd64"
あー、そもそも dkms パッケージなのでソースコードしか含まれていないと…？

2023-05-08 16:30 UTC, kazuki0824 commented on README.md
> +sudo apt install px4-drv*.deb -y
確かにその通りですね。直しておきます。

2023-05-08 16:51 UTC, kazuki0824 commented on build_deb.sh
> +ARCH="amd64"
今見てみましたが、dkms mkdeb は自動でアーキを判定して名前設定してくれるようです。
一方自らcontrolを書いて作っているバイナリブロブのパッケージは Architecture: allなので、ファイルが***_all.debと命名されるよう修正します

2023-05-09 10:58 UTC, tsukumijima requested changes

2023-05-09 10:58 UTC, tsukumijima commented on build_deb.sh
> +sudo apt install dkms dpkg
全体的にパスが installer のままで修正されていなさそうです。
また、生成時に発生する一時ファイルは .gitignore に追加したり、明らかに不要であれば生成後に削除したりする方が適切だと思います。

また、現在コメントアウトされている箇所は基本使われないと思うので、削除してしまった方が良いように思います。

…そもそも dkms のパッケージ自体に it930x-firmware.bin を含めてしまえば2つパッケージを DL する必要がなくなりインストールが楽になると思ったのですが、どうでしょうか？

2023-05-09 10:58 UTC, tsukumijima commented on README.md
> +#### ビルド済みバイナリをDebianパッケージからインストールする
以前レビューさせていただいた内容が反映されていないようです。

2023-05-10 15:40 UTC, kazuki0824 commented on build_deb.sh
> +sudo apt install dkms dpkg
> 全体的にパスが installer のままで修正されていなさそうです。
また、生成時に発生する一時ファイルは .gitignore に追加したり、明らかに不要であれば生成後に削除したりする方が適切だと思います。
これはそのとおりですね。これは/tmp以下に作業ファイル群を作る方針に変えようと思います。


> また、現在コメントアウトされている箇所は基本使われないと思うので、削除してしまった方が良いように思います。
確かにそうですね。また、コメントであえて残すということは、通常実行されないのにメンテはしないといけないということになり面倒ですね。消すようにします。

> …そもそも dkms のパッケージ自体に it930x-firmware.bin を含めてしまえば2つパッケージを DL する必要がなくなりインストールが楽になると思ったのですが、どうでしょうか？
これはdkms mkdebを利用してpx4-drv-dkmsを生成している事に起因します。
dkms mkdebを使用するとdkmsへの依存指定とトリガーを効かせたdebパッケージがかんたんに作れるのです。しかし私の知る限り、mkdebサブコマンドは特定のパスへインストールするファイルを追加指定する手段を持ちません。そこで、/lib/firmwareにバイナリブロブを配置するパッケージと、ソースをdkms込みで配置するパッケージの２つに分けています。
（ちなみにあのnvidia-driverとかもnvidia-kernel-commonとnvidia-kernel-sourceに別れていて、こんな感じの構成です）
頑張れば美しくひとまとめにできると思いますが、果たして労力に見合うかなぁという気はしています。

2023-05-10 16:46 UTC, kazuki0824 commented on README.md
> +#### ビルド済みバイナリをDebianパッケージからインストールする
> あと、英字やコードと日本語との間には半角スペースを1つ空けてください。
また、周囲同様に見出し前の改行は1つ、見出し後の改行も1つに統一したいです。

これですね！

2023-05-11 14:00 UTC, tsukumijima commented on build_deb.sh
> +sudo apt install dkms dpkg
> 現在、生成後に削除する仕様にすでになっているかと思いますが、機能してないですか？

これに関しては再度確認したところ、問題なさそうです。

> 私の知る限り、mkdebサブコマンドは特定のパスへインストールするファイルを追加指定する手段を持ちません。

確かに dkms mkdeb はファイルを追加指定する手段がないようですが、px4_drv では既に `dkms install` 実行時に自動的に udev ルールファイル (99-px4video.rules) がインストールされるようになっています。

この仕組みを応用して、dkms のインストール/アンインストールプロセス自体にファームウェアバイナリのインストールプロセスを含めることで解決できそうに思います。
ただし、これを行う場合は通常の dkms でのインストール方法も変わるため、Readme を調整する必要があります。
また、一貫性のために、Makefile を使ってインストールする方法でも インストール/アンインストール時にファームウェアバイナリをインストールするように変更した方が良いでしょう。

また、この際にファームウェアファイルは 99-px4video.rules と同じ etc ディレクトリ以下にコピーして配置してしまった方が、分かりやすさの面で良さそうです (winusb 以下はあくまで Windows 用なので…)。

-----

…まとめると、こちらとしては

- ファームウェアバイナリはわざわざ抽出する必要性が皆無 (安定性上一番望ましいファームウェアが既に決まっている)
- 前述の通り、ファームウェア抽出は PLEX の Windows 向け旧ドライバの URL に依存しており、もし仮に削除された場合に動作しなくなる
- たった1つのファームウェアファイルのために別で deb パッケージを作るのは煩わしい
- ファームウェアを別個で抽出してインストールしている現状のインストール方法自体も煩わしい（とはいえコマンドコピペするだけではあるが…）

ということで、

- Makefile でのインストール、dkms でのインストールの両方で、ファームウェアファイルを etc/iit930x-firmware.bin からシステムにインストールされるように実装する
- Readme のインストール手順から「1. ファームウェアの抽出とインストール」の記述を削除し、「2. ドライバのインストール」内のコマンドだけで Makefile / dkms ともにインストールできるようにする
- ここまで来れば `dkms mkdeb` を実行するだけで dkms とファームウェアがセットになった deb パッケージが生成されるはずなので、今のファームウェア用 deb パッケージの生成機構を削除する

とした方が全体的にシンプルになって良いと思うのですが、どうでしょうか？

2023-05-14 16:18 UTC, kazuki0824 commented on build_deb.sh
> +sudo apt install dkms dpkg
パッケージを一本化する事以外は全面的に賛成です。
パッケージをひとまとめにすることについては、私の方でも調べを進めているもののスマートに実現する方法が見つけられていない状況です。なにか良い方法があればご教授いただけると助かります。

2023-05-15 13:42 UTC, tsukumijima commented on build_deb.sh
> +sudo apt install dkms dpkg
私は上記の方法が一番スマートではないかと考えていますが、もし実装が面倒などあれば一旦私の方でマージしてこちらで引き取ることも可能です。
（最初からそうしてしまってもよかったのですが、あまりプルリクをレビューする側になったことがないのもあって折角の機会だしとレビューし始めた結果、だいぶやりとりが長くなってしまって申し訳ないです…）

ファームウェアファイルはドライバと不可分ですから、同じくドライバと不可分な udev ルールファイルと同様に dkms の対象に含めてしまうのが手っ取り早いのではないかと思っています。

2023-05-15 15:48 UTC, kazuki0824 commented on build_deb.sh
> +sudo apt install dkms dpkg
> 私は上記の方法が一番スマートではないかと考えていますが、もし実装が面倒などあれば一旦私の方でマージしてこちらで引き取ることも可能です。

すみません私の力及ばずです、、、一旦引き取ってくださると助かります。私も引き続き調べてみます。


> だいぶやりとりが長くなってしまって申し訳ないです…）

謝る必要はありません...！美しさは正義です。

2023-05-15 16:14 UTC, merged

2023-05-15 16:14 UTC, tsukumijima commented
ひとまずマージしました。ありがとうございました！